import type { StudentDetail, StudentSummary } from "./students";

const baseStudents: StudentSummary[] = [
  {
    customerid: 48219,
    name: "Jamie",
    lname: "Rivera",
    email: "jamie.rivera@example.test",
    mobilenum: "(916) 555-0142",
    Classification: "B",
    account_type: 1,
    account_status: 1,
    disabled: false,
    address: "1840 J Street",
    city: "Sacramento",
    state: "CA",
    zip: "95811",
    firsttime: 1,
    orderdate: "2026-07-18",
    extension_date: "2027-07-18",
    re_enrollment_date: null,
    Notes: "Prefers text messages after 3 PM.",
    test_date_law: "2026-09-21",
    test_date_trade: "2026-09-23",
    new_test_date: null,
    created_at: "2026-07-18T16:24:00Z",
  },
  {
    customerid: 48177,
    name: "Morgan",
    lname: "Lee",
    email: "morgan.lee@example.test",
    mobilenum: "(209) 555-0188",
    Classification: "C-10",
    account_type: 1,
    account_status: 1,
    disabled: false,
    address: "92 West Oak Avenue",
    city: "Stockton",
    state: "CA",
    zip: "95202",
    firsttime: 3,
    orderdate: "2026-07-02",
    extension_date: "2027-07-02",
    re_enrollment_date: null,
    Notes: null,
    test_date_law: null,
    test_date_trade: null,
    new_test_date: null,
    created_at: "2026-07-02T19:05:00Z",
  },
  {
    customerid: 47961,
    name: "Avery",
    lname: "Patel",
    email: "avery.patel@example.test",
    mobilenum: "(408) 555-0130",
    Classification: "C-33",
    account_type: 0,
    account_status: 1,
    disabled: false,
    address: "514 Willow Lane",
    city: "San Jose",
    state: "CA",
    zip: "95112",
    firsttime: 0,
    orderdate: null,
    extension_date: null,
    re_enrollment_date: null,
    Notes: "Demo account; requested a course comparison.",
    test_date_law: null,
    test_date_trade: null,
    new_test_date: null,
    created_at: "2026-06-11T17:45:00Z",
  },
  {
    customerid: 47784,
    name: "Sofia",
    lname: "Martinez",
    email: "sofia.martinez@example.test",
    mobilenum: "(323) 555-0176",
    Classification: "C-54",
    account_type: 1,
    account_status: 0,
    disabled: true,
    address: "803 Mariposa Street",
    city: "Los Angeles",
    state: "CA",
    zip: "90005",
    firsttime: 5,
    orderdate: "2026-05-22",
    extension_date: "2026-08-22",
    re_enrollment_date: null,
    Notes: "Account paused after duplicate enrollment review.",
    test_date_law: "2026-10-06",
    test_date_trade: null,
    new_test_date: null,
    created_at: "2026-05-22T21:11:00Z",
  },
  {
    customerid: 47402,
    name: "Noah",
    lname: "Williams",
    email: "noah.williams@example.test",
    mobilenum: "(530) 555-0109",
    Classification: "A",
    account_type: 1,
    account_status: 1,
    disabled: false,
    address: "44 Pine Ridge Road",
    city: "Chico",
    state: "CA",
    zip: "95928",
    firsttime: 1,
    orderdate: "2026-04-09",
    extension_date: "2027-04-09",
    re_enrollment_date: null,
    Notes: null,
    test_date_law: "2026-09-30",
    test_date_trade: "2026-10-02",
    new_test_date: null,
    created_at: "2026-04-09T15:30:00Z",
  },
];

export const studentFixtures: StudentDetail[] = baseStudents.map((student, index) => ({
  ...student,
  previous_email: index === 0 ? "jrivera@example.test" : null,
  mobilenum_extension: null,
  company_name: index === 0 ? "Rivera Builders" : null,
  fee_license: index === 0 ? "APP-284991" : null,
  application_date: index === 0 ? "2026-08-03" : null,
  app_review_expiration_date: index === 0 ? "2027-07-18" : null,
  es_access: index === 3 ? 1 : 0,
  iapp_access: index === 0 ? 2 : index === 2 ? 0 : 1,
  prescreen_choice: index === 0 ? "ORIGINAL_LICENSE" : null,
  apps_account_created: index === 0,
  documents: index === 0 ? [{ id: 71, description: "Signed enrollment agreement", date: "2026-07-18", admin_name: "AE" }] : [],
  online_courses: index === 0 ? [{ id: 912, clas_id: 1, end_enroll: "2027-07-18", status: 1 }] : [],
  live_classes: index === 0 ? [{ id: 205, live_class_category_id: 4, end_enroll: "2026-10-31", status: 1 }] : [],
  class_managements: index === 0 ? [{ id: 340, sem_location: "Sacramento", law_date: "2026-09-08", trade_date: "2026-09-10", confirmed: 1, initials: "AE" }] : [],
  subscribed_tests: index === 0 ? [{ id: 601, access_lev: 1, expiration_date: "2027-07-18", status: 1 }] : [],
  notes: index === 0 ? [{ id: 401, notes: "Confirmed mailing address and class dates.", admin: "AE", date_value: "2026-08-28", date_time: "14:20" }] : [],
  corporation: index === 0 ? { id: 88, name: "Rivera Builders Inc.", entity_type: "S Corporation", city: "Sacramento", state: "CA", phone: "(916) 555-0142", email: "jamie.rivera@example.test" } : null,
}));

export function fixtureStudent(id: number) {
  return studentFixtures.find((student) => student.customerid === id) ?? null;
}
